---
- name: Config edgerouter4
  hosts: edgerouter4
  remote_user: ansible_sa
  become: true

  vars:
    node_exporter_version: 1.5.0
    node_exporter_arch: mips64
    node_exporter_bin_path: /usr/bin/node_exporter
    node_exporter_options:
      --collector.systemd 
      --collector.logind
      --no-collector.bonding
      --no-collector.hwmon
      --no-collector.infiniband
      --no-collector.ipvs
      --no-collector.mdadm
      --no-collector.nfs
      --no-collector.nfsd
      --no-collector.powersupplyclass
      --no-collector.zfs
      --no-collector.xfs
      --no-collector.thermal_zone
      --no-collector.schedstat
      --no-collector.rapl
      --no-collector.btrfs
      --no-collector.bcache
      --no-collector.cpufreq
      --no-collector.edac

  tasks:

    - name: Install node_exporter for Prometheus metrics collection
      ansible.builtin.include_role:
        name: geerlingguy.node_exporter