---
- name: Config edgerouter4 authorization
  hosts: edgerouter4
  remote_user: ubnt
  become: true

  tasks:

    - name: Setup ssh config
      when:
        - public_key_path is defined
        - public_key_path != ''
        - private_key_path is defined
        - private_key_path != ''
      block:
        - name: Setup authorized_keys
          ansible.posix.authorized_key:
            user: ubnt
            key: "{{ lookup('file', public_key_path) }}"

        - name: Remove ansible_ssh_pass to switch to key-based auth
          ansible.builtin.set_fact:
            ansible_ssh_pass: null
            ansible_ssh_private_key_file: "{{ private_key_path }}"

- name: Config edgerouter4
  hosts: edgerouter4
  remote_user: ubnt
  connection: network_cli
  tags:
    - router_config

  vars_files:
    - pwd.yaml

  tasks:
    - name: Gather edgeos facts
      community.network.edgeos_facts:
        gather_subset:
          - config

    - name: Print edgeos version
      ansible.builtin.debug:
        var: ansible_net_version

    - name: Backup configuration
      community.network.edgeos_config:
        backup: true
        backup_options:
          dir_path: /tmp
      register: edgeos_backup_location

    # - name: Add system image
    #   ansible.builtin.command:
    #     cmd: add system image https://dl.ui.com/firmwares/edgemax/v2.0.9-hotfix.6/ER-e300.v2.0.9-hotfix.6.5574652.tar
    #   register: image_add

    - name: Debug message
      ansible.builtin.debug:
        msg: "backup location: {{ edgeos_backup_location }}"

    - name: Configure edgeos
      community.network.edgeos_config:
        src: templates/edgerouter_config.j2
        save: true
        comment: ansible config

- name: Additional Installs
  hosts: edgerouter4
  remote_user: ubnt
  become: true

  vars_files:
    - node_exporter.yaml

  roles:
    - role: geerlingguy.node_exporter
